### PR TITLE
Added Speed of Sound Keys Upgrade

### PR DESCRIPTION
**Pull request by BowlsforRick**

### CODE REVIEW

**Comment by LinosM** [comment]
* Remember the track order needed
`K
PK_E
PK_E
PK_M
PK_H
PK_X`

* Move all "E2-G3" range markers up to "F3-A3", move all "A2-C4" range markers down to "G2-B3"

* 67: The B3 can be restored here on both PK_H & PK_X

* Expert and Hard 5L need their chord sustains pulled back

* Medium 5L chords need to be looked at and redone:

G/Y chords are being repeated for different chords (see 16:19, 47-48, 51-52, 123-124 are examples)

Consider shifting all instances of "G/Y - A major" chords up to R/Y, all "G/R - E minor" chords up to G/Y, and shift all "G/Y - D major" chords down to G/R

During every chorus, consider shifting all chords to their highest points, 
Before:
before
After:
after

* There is a Medium reduction inconsistency between 5L and Pro during the piano intro and all repeated instances of it. Have Pro match 5L's reduction

* 35, 76: These notes are just flat-out missing on PK_M and PK_E
  * On both 5L and Pro, have Hard match Expert
  * Medium: Restore every note that's on a 1/4 grid
  * Easy: Keep only the note on X.3.50

* Have trainer 4 end on 60.1.00

**Comment by BowlsforRick** [comment]
Changes have been applied to midi file

**Comment by LinosM** [comment]
* You moved the verses to match the picture when I said to only do that for the choruses

This comment earlier applies to the verses:
`Consider shifting all instances of "G/Y - A major" chords up to R/Y, all "G/R - E minor" chords up to G/Y, and shift all "G/Y - D major" chords down to G/R`

* You matched the Pro Medium piano intro (and repeat) to Easy 5L and not Medium 5L

* 35, 76 Easy: This was my mistake, I meant to say X.3.00, not X.3.50

* 52-58, 93-99 Easy 5L: move all the Y/B/O's down 1 note
* 60-67, 101-112, 128-133 Easy 5L: Move the Y/B's to B/O, move the G's to Y
* 135-141 Easy 5L: Fix this inconsistency and match the notes to the choruses

* 120-127 All 5L: Match this:
reaper_r3HwYQtYhY

**Comment by BowlsforRick** [comment]
Not sure what I was doing with the last fix, sorry about that. Just fixed up the midi now should be good now.

**Pull request merged**
